/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sunway
 */
public class rsl3sq extends javax.swing.JFrame {

    /**
     * Creates new form rsl1e
     */
    public rsl3sq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 430));
        setMinimumSize(new java.awt.Dimension(720, 430));
        setPreferredSize(new java.awt.Dimension(720, 430));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verana", 3, 24)); // NOI18N
        jLabel2.setText("Total questions :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 230, 30);

        jLabel3.setFont(new java.awt.Font("Verana", 3, 24)); // NOI18N
        jLabel3.setText("Total stars :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 50, 200, 40);

        jLabel4.setFont(new java.awt.Font("Verana", 3, 24)); // NOI18N
        jLabel4.setText("Your performance:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 260, 260, 30);
        getContentPane().add(t3);
        t3.setBounds(320, 260, 180, 29);

        jButton1.setFont(new java.awt.Font("Verana", 3, 24)); // NOI18N
        jButton1.setText("quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 310, 100, 41);

        jLabel5.setFont(new java.awt.Font("URW Chancery L", 3, 40)); // NOI18N
        jLabel5.setText("5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 50, 49, 30);

        jLabel6.setFont(new java.awt.Font("URW Chancery L", 3, 40)); // NOI18N
        jLabel6.setText("* * * * *");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 50, 150, 52);

        jButton3.setFont(new java.awt.Font("Verana", 3, 24)); // NOI18N
        jButton3.setText("back to home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 310, 210, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot from 2019-11-25 08-31-52.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(720, 430));
        jLabel1.setMinimumSize(new java.awt.Dimension(720, 430));
        jLabel1.setPreferredSize(new java.awt.Dimension(720, 430));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     quiztypes q=new quiztypes();
        q.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rsl1e.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rsl1e.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rsl1e.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rsl1e.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rsl3e1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
