
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sunway
 */
public class SQ2 extends javax.swing.JFrame {

    /**
     * Creates new form SQ2
     */
    public SQ2() {
        initComponents();
    }int counter=10;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        R2 = new javax.swing.JRadioButton();
        R5 = new javax.swing.JRadioButton();
        R6 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        B1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        time1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        R1 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        B = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(764, 377));
        jFrame1.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("URW Bookman L", 3, 36)); // NOI18N
        jLabel3.setText("What was the olympic city of1992?  ");
        jFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 30, 630, 50);

        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        R2.setText("Barcelona ");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(R2);
        R2.setBounds(50, 120, 190, 41);

        buttonGroup1.add(R5);
        R5.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        R5.setText("Tokyo");
        R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(R5);
        R5.setBounds(50, 270, 130, 41);

        buttonGroup1.add(R6);
        R6.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        R6.setText("stockholm");
        R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(R6);
        R6.setBounds(50, 220, 170, 41);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        r3.setText("sweden");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r3);
        r3.setBounds(50, 170, 190, 41);

        B1.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        B1.setText("NEXT");
        B1.setEnabled(false);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(B1);
        B1.setBounds(350, 310, 100, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIME LEFT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dustismo Roman", 3, 30))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(71, 74));
        jPanel2.setMinimumSize(new java.awt.Dimension(71, 74));
        jPanel2.setPreferredSize(new java.awt.Dimension(71, 74));

        time1.setMaximumSize(new java.awt.Dimension(49, 20));
        time1.setMinimumSize(new java.awt.Dimension(49, 20));
        time1.setPreferredSize(new java.awt.Dimension(49, 20));
        jPanel2.add(time1);

        jFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(550, 100, 190, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot from 2019-07-26 09-38-08.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(764, 377));
        jLabel4.setMinimumSize(new java.awt.Dimension(764, 377));
        jLabel4.setPreferredSize(new java.awt.Dimension(764, 377));
        jFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 764, 370);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(746, 440));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 3, 36)); // NOI18N
        jLabel1.setText("What was the olympic city of1992?  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 630, 50);

        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        R1.setText("Barcelona ");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1);
        R1.setBounds(50, 120, 190, 41);

        buttonGroup1.add(R4);
        R4.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        R4.setText("Tokyo");
        R4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4ActionPerformed(evt);
            }
        });
        getContentPane().add(R4);
        R4.setBounds(50, 270, 130, 41);

        buttonGroup1.add(R3);
        R3.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        R3.setText("stockholm");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });
        getContentPane().add(R3);
        R3.setBounds(50, 220, 170, 41);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        r2.setText("sweden");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(50, 170, 190, 41);

        B.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        B.setText("NEXT");
        B.setEnabled(false);
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        getContentPane().add(B);
        B.setBounds(350, 310, 100, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIME LEFT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dustismo Roman", 3, 30))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(71, 74));
        jPanel1.setMinimumSize(new java.awt.Dimension(71, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(71, 74));

        time.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        time.setMaximumSize(new java.awt.Dimension(49, 20));
        time.setMinimumSize(new java.awt.Dimension(49, 20));
        time.setPreferredSize(new java.awt.Dimension(49, 20));
        jPanel1.add(time);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 100, 190, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot from 2019-07-26 09-38-08.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(746, 440));
        jLabel2.setMinimumSize(new java.awt.Dimension(746, 440));
        jLabel2.setPreferredSize(new java.awt.Dimension(746, 440));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 746, 370);

        score.setText("jLabel5");
        getContentPane().add(score);
        score.setBounds(310, 180, 59, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        
        {        int points;
    if (r2.isSelected())
    {points=1;}
    else 
        points=0;
   
    sq3 q=new sq3();
    q.setVisible (true);}
        dispose();
    }//GEN-LAST:event_BActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        B.setEnabled(true);      score.setText(""+0);
    }//GEN-LAST:event_R1ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
         B.setEnabled(true);      score.setText(""+0);
    }//GEN-LAST:event_R3ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
      B.setEnabled(true);      score.setText(""+1);
    }//GEN-LAST:event_r2ActionPerformed

    private void R4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4ActionPerformed
         B.setEnabled(true);      score.setText(""+0);
    }//GEN-LAST:event_R4ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2ActionPerformed

    private void R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R5ActionPerformed

    private void R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R6ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Timer timer=new Timer();
TimerTask task=new TimerTask(){

    public void run() {
     time.setText(""+counter);
     counter--;
if (counter==-1)
{
    JOptionPane.showMessageDialog(null,"time out");
}
    } };
   timer.scheduleAtFixedRate(task, 1000, 1000);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SQ2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B;
    private javax.swing.JButton B1;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton R4;
    private javax.swing.JRadioButton R5;
    private javax.swing.JRadioButton R6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JLabel score;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time1;
    // End of variables declaration//GEN-END:variables
}
