/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sunway
 */
public class tq4 extends javax.swing.JFrame {

    /**
     * Creates new form tq1
     */
    public tq4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        b = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(697, 435));
        setMinimumSize(new java.awt.Dimension(697, 435));
        setPreferredSize(new java.awt.Dimension(697, 435));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("URW Bookman L", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 44, 215));
        jLabel2.setText("How many bits forms a Byte?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 750, 40);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        r1.setForeground(new java.awt.Color(54, 44, 215));
        r1.setText("Four");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(20, 140, 290, 36);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        r3.setForeground(new java.awt.Color(54, 44, 215));
        r3.setText("Sixteen");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3);
        r3.setBounds(20, 240, 103, 30);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        r2.setForeground(new java.awt.Color(54, 44, 215));
        r2.setText("Eight");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(20, 190, 440, 30);

        b.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        b.setForeground(new java.awt.Color(54, 44, 215));
        b.setText("NEXT");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(370, 370, 110, 44);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(54, 44, 215));
        jRadioButton2.setText("Thirty two");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 280, 230, 36);

        jLabel1.setFont(new java.awt.Font("URW Palladio L", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 42, 224));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot from 2019-07-31 12-29-02.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(780, 438));
        jLabel1.setMinimumSize(new java.awt.Dimension(780, 438));
        jLabel1.setPreferredSize(new java.awt.Dimension(780, 438));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 760, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
         b.setEnabled(true);
    }//GEN-LAST:event_r1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
                         
               int points;
    if (r2.isSelected())
    {points=1;}
    else 
        points=0;
   rstq1 r=new rstq1();
   r.score1(points);
    tq5 q=new tq5();
    q.setVisible (true);
        dispose();
    }//GEN-LAST:event_bActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
         b.setEnabled(true);
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
         b.setEnabled(true);
    }//GEN-LAST:event_r3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tq4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    // End of variables declaration//GEN-END:variables
}
